---
- hosts: leafs_DC1, leafs_DC2
  name: Generate interface part of the config
  tasks:
    - name: Load YAML into dictionary
      include_vars: 
        file: "{{lookup('env','PWD')}}/vars/underlay.yml"
        name: underlay
    - name: Load YAML for VXLAN into dictionary
      include_vars: 
        file: "{{lookup('env','PWD')}}/vars/VXLAN.yml"
        name: VXLAN
    - name: Gen interface file
      template:
        src: "{{lookup('env','PWD')}}/templates/VXLAN.j2"
        dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_VXLAN.cfg"